dependencies:
  # tell brownie to download link contracts from github instead of npm
  # https://github.com/smartcontractkit/chainlink-brownie-contracts
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1" # tell the compiler what @chainlink means

dotenv: .env
networks:
  goerli:
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
    verify: True
  development:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
